package seguridad.vista;

import com.formdev.flatlaf.FlatDarkLaf;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import proceso.vista.proceso_recuperacion;
import seguridad.dominio.Usuario;

import seguridad.dominio.Permisos;
import seguridad.dominio.Usuario;

/**
 *
 * @author 
 */
public class contenedor extends javax.swing.JFrame {

private proceso_recuperacion proceso_recuperacion; 
    private FmrBitacora formFmrBitacora;

    /**
     * Creates new form MDI_Seguridad
     *
     * @throws java.net.UnknownHostException
     */
    MDI_Components mdi_components = new MDI_Components();

 

    /*------------------------------------------*/
    public contenedor() throws UnknownHostException {
        initComponents();

        this.setTitle("Usuario: " + "[" + Login.usuarioSesion + "]" + " \t" + "IP: [" + mdi_components.getIp() + "]");

        var usuario = Login.usuarioSesion;
        var modulo = "Seguridad";

        //generarPermisos.getPermisos(modulo, usuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDesktopPane_Escritorio = new javax.swing.JDesktopPane()
        ;
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu_Archivo = new javax.swing.JMenu();
        JMenuItem_CerrarSesion = new javax.swing.JMenuItem();
        JMenu_Seguridad = new javax.swing.JMenu();
        JMenu_Asignaciones = new javax.swing.JMenu();
        JMenuItem_PerfilesUsuarios = new javax.swing.JMenuItem();
        JMenuItem_AplicacionesModulos = new javax.swing.JMenuItem();
        JMenuItem_Bitacora = new javax.swing.JMenuItem();
        JMenu_Mantenimientos = new javax.swing.JMenu();
        JMenuItem_Usuarios = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Hotelero");
        setResizable(false);

        JDesktopPane_Escritorio.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Carlos Alberto Flores  De  paz  9959-19-186");

        JDesktopPane_Escritorio.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JDesktopPane_EscritorioLayout = new javax.swing.GroupLayout(JDesktopPane_Escritorio);
        JDesktopPane_Escritorio.setLayout(JDesktopPane_EscritorioLayout);
        JDesktopPane_EscritorioLayout.setHorizontalGroup(
            JDesktopPane_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDesktopPane_EscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(544, Short.MAX_VALUE))
        );
        JDesktopPane_EscritorioLayout.setVerticalGroup(
            JDesktopPane_EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDesktopPane_EscritorioLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(jLabel1)
                .addContainerGap(601, Short.MAX_VALUE))
        );

        JMenu_Archivo.setText("Archivo");
        JMenu_Archivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        JMenuItem_CerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_CerrarSesion.setText("Cerrar Sesión");
        JMenuItem_CerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_CerrarSesionActionPerformed(evt);
            }
        });
        JMenu_Archivo.add(JMenuItem_CerrarSesion);

        jMenuBar1.add(JMenu_Archivo);

        JMenu_Seguridad.setText("Seguridad");
        JMenu_Seguridad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        JMenu_Asignaciones.setText("Asignaciones");
        JMenu_Asignaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        JMenuItem_PerfilesUsuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_PerfilesUsuarios.setText("Perfiles - Usuarios");
        JMenuItem_PerfilesUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_PerfilesUsuariosActionPerformed(evt);
            }
        });
        JMenu_Asignaciones.add(JMenuItem_PerfilesUsuarios);

        JMenuItem_AplicacionesModulos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_AplicacionesModulos.setText("Aplicaciones - Módulos");
        JMenuItem_AplicacionesModulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_AplicacionesModulosActionPerformed(evt);
            }
        });
        JMenu_Asignaciones.add(JMenuItem_AplicacionesModulos);

        JMenu_Seguridad.add(JMenu_Asignaciones);

        JMenuItem_Bitacora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_Bitacora.setText("Bitácora");
        JMenuItem_Bitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_BitacoraActionPerformed(evt);
            }
        });
        JMenu_Seguridad.add(JMenuItem_Bitacora);

        JMenu_Mantenimientos.setText("Mantenimientos");
        JMenu_Mantenimientos.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        JMenuItem_Usuarios.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        JMenuItem_Usuarios.setText("Usuarios");
        JMenuItem_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItem_UsuariosActionPerformed(evt);
            }
        });
        JMenu_Mantenimientos.add(JMenuItem_Usuarios);

        JMenu_Seguridad.add(JMenu_Mantenimientos);

        jMenuBar1.add(JMenu_Seguridad);

        jMenu1.setText("Procesos");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem1.setText("Recuperacion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPane_Escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPane_Escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void JMenuItem_CerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_CerrarSesionActionPerformed
        /*===== OPERACIÓN CERRAR SESIÓN ====
          Variable entera respuesta_cs*/

        int respuesta_cs = JOptionPane.showConfirmDialog(this, "¿Desea Cerrar Sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);

        if (respuesta_cs == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_JMenuItem_CerrarSesionActionPerformed


    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
      


    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void JMenuItem_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_UsuariosActionPerformed

    }//GEN-LAST:event_JMenuItem_UsuariosActionPerformed

    private void JMenuItem_BitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_BitacoraActionPerformed
        formFmrBitacora = new FmrBitacora();
        formFmrBitacora.setVisible(true);
        JDesktopPane_Escritorio.add(formFmrBitacora);
    }//GEN-LAST:event_JMenuItem_BitacoraActionPerformed

    private void JMenuItem_AplicacionesModulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_AplicacionesModulosActionPerformed
        //  Asignacionmodulos Rita Sipaque

    }//GEN-LAST:event_JMenuItem_AplicacionesModulosActionPerformed

    private void JMenuItem_PerfilesUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItem_PerfilesUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuItem_PerfilesUsuariosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
   proceso_recuperacion = new proceso_recuperacion();
        proceso_recuperacion.setVisible(true);
        JDesktopPane_Escritorio.add(proceso_recuperacion);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new contenedor().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(contenedor.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDesktopPane_Escritorio;
    public static javax.swing.JMenuItem JMenuItem_AplicacionesModulos;
    public static javax.swing.JMenuItem JMenuItem_Bitacora;
    private javax.swing.JMenuItem JMenuItem_CerrarSesion;
    public static javax.swing.JMenuItem JMenuItem_PerfilesUsuarios;
    public static javax.swing.JMenuItem JMenuItem_Usuarios;
    public javax.swing.JMenu JMenu_Archivo;
    public static javax.swing.JMenu JMenu_Asignaciones;
    public static javax.swing.JMenu JMenu_Mantenimientos;
    public javax.swing.JMenu JMenu_Seguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
